import fs from 'node:fs';
import path from 'node:path';
import chalk from 'chalk';
import { confirm, select, input } from '@inquirer/prompts';
import { scanCodebase } from './scanner.js';

const TYPE_CHOICES = [
  { name: 'string', value: 'string' },
  { name: 'number', value: 'number' },
  { name: 'boolean', value: 'boolean' },
  { name: 'url', value: 'url' },
  { name: 'email', value: 'email' },
];

/**
 * Runs the interactive setup wizard: scans the codebase for
 * process.env usage, walks the user through choosing which to
 * document (with a type + optional description each), writes
 * .env.example, and optionally scaffolds a config file with a
 * `validate` schema built from the chosen types.
 *
 * @param {string} dir - project root to scan and write into
 * @returns {Promise<{ exampleWritten: boolean, configWritten: boolean, varsAdded: string[] }>}
 */
export async function runInitWizard(dir) {
  console.log(chalk.cyan('Scanning codebase for process.env usage...'));
  const { codeVars } = await scanCodebase(dir);
  const names = [...codeVars.keys()].sort();

  if (names.length === 0) {
    console.log(chalk.yellow('No process.env usage found in this project — nothing to set up.'));
    return { exampleWritten: false, configWritten: false, varsAdded: [] };
  }

  console.log(chalk.green(`Found ${names.length} environment variable${names.length === 1 ? '' : 's'}.`));

  const proceed = await confirm({
    message: `Generate .env.example from these ${names.length} variable${names.length === 1 ? '' : 's'}?`,
    default: true,
  });

  if (!proceed) {
    console.log(chalk.dim('Cancelled — nothing was written.'));
    return { exampleWritten: false, configWritten: false, varsAdded: [] };
  }

  const examplePath = path.join(dir, '.env.example');
  if (fs.existsSync(examplePath)) {
    const overwrite = await confirm({
      message: `.env.example already exists at ${path.relative(dir, examplePath) || '.env.example'} — overwrite it?`,
      default: false,
    });
    if (!overwrite) {
      console.log(chalk.dim('Cancelled — .env.example was left untouched.'));
      return { exampleWritten: false, configWritten: false, varsAdded: [] };
    }
  }

  const entries = []; // { name, type, description }

  for (const name of names) {
    const include = await confirm({ message: `${name} — add to .env.example?`, default: true });
    if (!include) continue;

    const type = await select({
      message: `${name} — expected type?`,
      choices: TYPE_CHOICES,
      default: 'string',
    });

    const description = await input({
      message: `${name} — add a description comment? (optional)`,
      default: '',
    });

    entries.push({ name, type, description: description.trim() });
  }

  if (entries.length === 0) {
    console.log(chalk.dim('No variables selected — nothing was written.'));
    return { exampleWritten: false, configWritten: false, varsAdded: [] };
  }

  const exampleBody = entries
    .map(({ name, type, description }) => {
      const lines = [];
      if (description) lines.push(`# ${description}`);
      lines.push(`# Type: ${type}`);
      lines.push(`${name}=`);
      return lines.join('\n');
    })
    .join('\n\n');

  fs.writeFileSync(examplePath, exampleBody + '\n', 'utf8');
  console.log(chalk.green(`✔ Wrote ${entries.length} variable${entries.length === 1 ? '' : 's'} to .env.example`));

  const wantsConfig = await confirm({
    message: 'Generate envscan-cli.config.js with your type definitions?',
    default: true,
  });

  let configWritten = false;
  if (wantsConfig) {
    const validateEntries = entries.filter((e) => e.type !== 'string');
    const validateBlock = validateEntries.length > 0
      ? validateEntries.map((e) => `    ${e.name}: '${e.type}',`).join('\n')
      : '';

    const configPath = path.join(dir, 'envscan-cli.config.js');
    const configBody = `// envscan-cli.config.js
// Generated by \`npx envscan-cli --init\` on ${new Date().toISOString().slice(0, 10)}

export default {
  ignore: [],
  exampleFile: '.env.example',
  ignoreUnused: false,
  secretDetection: true,
  required: [],
  validate: {
${validateBlock}
  },
};
`;

    if (fs.existsSync(configPath)) {
      const overwriteConfig = await confirm({
        message: 'envscan-cli.config.js already exists — overwrite it?',
        default: false,
      });
      if (overwriteConfig) {
        fs.writeFileSync(configPath, configBody, 'utf8');
        configWritten = true;
      }
    } else {
      fs.writeFileSync(configPath, configBody, 'utf8');
      configWritten = true;
    }

    if (configWritten) {
      console.log(chalk.green('✔ Wrote envscan-cli.config.js'));
    } else {
      console.log(chalk.dim('Skipped — envscan-cli.config.js was left untouched.'));
    }
  }

  console.log('');
  console.log(chalk.bold('Summary:'));
  console.log(`  .env.example: ${entries.length} variable${entries.length === 1 ? '' : 's'} written`);
  console.log(`  envscan-cli.config.js: ${configWritten ? 'written' : 'not created'}`);

  return { exampleWritten: true, configWritten, varsAdded: entries.map((e) => e.name) };
}
